twilio:
  account_sid: AC8a8e762a0162ac0247e180ab618a130f
  auth_token: 3e3a658ae7ed171bc04b9337217ea097
  service_id: VAd2f733f29448dba8adf6dc0841f83a45

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 207301066374-npoqhacd2ja1rbfl4ob1s1nc13ntg3ac.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile