twilio:
  account_sid: AC41ad6452fad0c7b763198fe5d9a3991c
  auth_token: d36be209ce23d72ae18b7c65c38d59b2
  service_id: VAc145d9687366253412c71f7a9d44c532

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 207301066374-npoqhacd2ja1rbfl4ob1s1nc13ntg3ac.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile