twilio:
  account_sid: AC8a8e762a0162ac0247e180ab618a130f
  auth_token: 51cd53b00e443a46b8338fef33397bca
  service_id: VAd2f733f29448dba8adf6dc0841f83a45

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 207301066374-npoqhacd2ja1rbfl4ob1s1nc13ntg3ac.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile